"""empty message

Revision ID: 14ee91292823
Revises: 3530e6c6a7d4
Create Date: 2015-12-20 12:10:17.346750

"""

# revision identifiers, used by Alembic.
revision = '14ee91292823'
down_revision = '3530e6c6a7d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketitem', 'logged')
    op.add_column('users', sa.Column('logged', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged')
    op.add_column('bucketitem', sa.Column('logged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
