"""empty message

Revision ID: 1b3d2d0c94de
Revises: 4a6dd9145552
Create Date: 2015-12-03 11:59:00.896966

"""

# revision identifiers, used by Alembic.
revision = '1b3d2d0c94de'
down_revision = '4a6dd9145552'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###
