"""empty message

Revision ID: 36190af796df
Revises: f7a69fec955
Create Date: 2015-11-28 15:39:51.916179

"""

# revision identifiers, used by Alembic.
revision = '36190af796df'
down_revision = 'f7a69fec955'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('reated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketitems')
    ### end Alembic commands ###
