"""empty message

Revision ID: 4a6dd9145552
Revises: 2fc243ea19c8
Create Date: 2015-11-30 10:14:42.282436

"""

# revision identifiers, used by Alembic.
revision = '4a6dd9145552'
down_revision = '2fc243ea19c8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['list'], ['bucketlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bucketitems')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketitems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modified_on', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'bucketitems_pkey')
    )
    op.drop_table('bucketitem')
    ### end Alembic commands ###
