"""empty message

Revision ID: 4fba230cfdd5
Revises: 1b3d2d0c94de
Create Date: 2015-12-04 07:41:57.818008

"""

# revision identifiers, used by Alembic.
revision = '4fba230cfdd5'
down_revision = '1b3d2d0c94de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlist', 'users', ['creator'], ['uid'])
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'bucketlist', type_='foreignkey')
    op.drop_column('bucketlist', 'creator')
    ### end Alembic commands ###
