"""empty message

Revision ID: 56715b423ca4
Revises: None
Create Date: 2015-12-05 08:59:41.560832

"""

# revision identifiers, used by Alembic.
revision = '56715b423ca4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bucketitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['list'], ['bucketlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketitem')
    op.drop_table('bucketlist')
    ### end Alembic commands ###
